services:
  rao-dev:
    build:
      context: .
      dockerfile: dev.dockerfile
    image: rao-dev
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/workspaces:cached
      - ~/.ssh:/root/.ssh
      - ./data:/data
      - gdrive:/data/gdrive

volumes:
  gdrive:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/run/user/1000/gvfs/google-drive:host=gmail.com,user=samuel.neugber/"
