services:
  rao:
    build:
      context: .
      dockerfile: deploy.dockerfile
    image: rao-runner
    entrypoint: rm-auto-ocr
    volumes:
      - ${HOME}/.ssh:/root/.ssh
      - ./data:/data
      # - gdrive:/data/gdrive

# volumes:
#   gdrive:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: # set me to e.g. "/run/user/1000/gvfs/google-drive:host=host.com,user=my.user/"