services:
  rao:
    build:
      context: .
      dockerfile: deploy.dockerfile
    image: rao-runner
    entrypoint: entrypoint.sh
    volumes:
      - ~/.ssh:/root/.ssh
      - ./data:/data
      - gdrive:/data/gdrive

volumes:
  gdrive:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "G:\\"
